name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: actions/setup-python@v4
        with:
          pyton-version: "3.12.4"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests